[build]
  command = "cd frontend && npm install && npm run build"
  publish = "frontend/dist"

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200
  force = true

[dev]
  command = "npm run dev --prefix frontend"
  targetPort = 5173
  port = 8888